/**
 * Data model for a display GUI layout.
 *
 * A layout is a tree of nodes. Containers lay out their children with
 * flexbox (row or column), every node has a `weight` that maps to
 * flex-grow, so the GUI scales to any screen size.
 *
 * The layout is stored as JSON in /userdata and rendered to a single,
 * self-contained HTML file that is served to the physical display.
 */

export type LayoutNodeType = 'container' | 'button' | 'slider' | 'label';

export interface BaseNode {
  /** Unique id within the layout (generated by the editor). */
  id: string;
  type: LayoutNodeType;
  /** Relative size within the parent container (flex-grow). Default 1. */
  weight?: number;
}

export interface ContainerNode extends BaseNode {
  type: 'container';
  direction: 'row' | 'column';
  /** Gap between children in px. */
  gap?: number;
  /** Padding inside the container in px. */
  padding?: number;
  /** Optional background color. */
  background?: string;
  children: LayoutNode[];
}

export interface ButtonNode extends BaseNode {
  type: 'button';
  /** Text shown on the button (may be empty when an image is used). */
  label: string;
  /**
   * Scene name sent to Homey when pressed. Triggers the
   * "scene-selected" Flow card with this name.
   */
  scene: string;
  /** Optional image URL (e.g. "cinema.png" from the public folder). */
  image?: string;
  /** Accent color used for the active state glow. */
  color?: string;
  fontSize?: number;
}

export interface SliderLevel {
  /** Label shown beside the slider. */
  name: string;
  /** Value (0-1) sent to the "light-level-changed" Flow trigger. */
  value: number;
}

export interface SliderNode extends BaseNode {
  type: 'slider';
  /**
   * Slider name sent to Homey with every level change, so multiple
   * sliders can be told apart in Flows. Defaults to "light".
   */
  name?: string;
  /**
   * Discrete levels, shown top to bottom (index 0 at the top).
   * Defaults to DEFAULT_SLIDER_LEVELS.
   */
  levels?: SliderLevel[];
  /**
   * @deprecated Legacy format: four label names with fixed values.
   * Superseded by `levels`; still accepted for stored layouts.
   */
  labels?: string[];
  /** Accent color of the slider handle while dragging. */
  color?: string;
}

export const MAX_SLIDER_LEVELS = 12;

export const DEFAULT_SLIDER_LEVELS: SliderLevel[] = [
  { name: 'OFF', value: 0 },
  { name: 'LOW', value: 0.05 },
  { name: 'MED', value: 0.5 },
  { name: 'FULL', value: 1 },
];

/**
 * Returns the levels of a slider node, converting the legacy `labels`
 * format and falling back to the defaults.
 */
export function sliderLevels(node: SliderNode): SliderLevel[] {
  if (Array.isArray(node.levels) && node.levels.length >= 2) {
    return node.levels;
  }
  if (Array.isArray(node.labels) && node.labels.length === DEFAULT_SLIDER_LEVELS.length) {
    return node.labels.map((name, i) => ({ name, value: DEFAULT_SLIDER_LEVELS[i].value }));
  }
  return DEFAULT_SLIDER_LEVELS;
}

export interface LabelNode extends BaseNode {
  type: 'label';
  text: string;
  fontSize?: number;
  color?: string;
  align?: 'left' | 'center' | 'right';
}

export type LayoutNode = ContainerNode | ButtonNode | SliderNode | LabelNode;

export interface ScreenSize {
  name: string;
  width: number;
  height: number;
}

export interface GuiLayout {
  version: 1;
  screen: ScreenSize;
  root: ContainerNode;
  /** Set by the server when the layout is saved. */
  updatedAt?: string;
}

/**
 * Screen sizes offered by the editor. The first two entries are the real
 * Shelly Wall Display models, the rest are mock sizes for testing other
 * screens.
 */
export const SCREEN_SIZES: ScreenSize[] = [
  { name: 'Shelly Wall Display (landscape)', width: 800, height: 480 },
  { name: 'Shelly Wall Display (portrait)', width: 480, height: 800 },
  { name: 'Shelly Wall Display X2 (landscape)', width: 1280, height: 800 },
  { name: 'Shelly Wall Display X2 (portrait)', width: 800, height: 1280 },
  { name: 'Mock: 7" tablet', width: 1024, height: 600 },
  { name: 'Mock: iPad', width: 1024, height: 768 },
  { name: 'Mock: Phone', width: 390, height: 844 },
  { name: 'Mock: Full HD', width: 1920, height: 1080 },
];

/**
 * Default layout replicating the original hard-coded GUI:
 * a light slider and two scene buttons (cinema and gym).
 */
export function createDefaultLayout(): GuiLayout {
  return {
    version: 1,
    screen: { ...SCREEN_SIZES[0] },
    root: {
      id: 'root',
      type: 'container',
      direction: 'row',
      gap: 16,
      padding: 16,
      children: [
        {
          id: 'light-1', type: 'slider', weight: 1, name: 'light', levels: DEFAULT_SLIDER_LEVELS.map((l) => ({ ...l })),
        },
        {
          id: 'btn-cinema',
          type: 'button',
          weight: 1,
          label: 'Cinema',
          scene: 'cinema',
          image: 'cinema.png',
        },
        {
          id: 'btn-gym',
          type: 'button',
          weight: 1,
          label: 'Gym',
          scene: 'gym',
          image: 'gym.png',
        },
      ],
    },
  };
}

const MAX_NODES = 500;
const MAX_DEPTH = 10;

/**
 * Validates an untrusted layout object (e.g. from the editor).
 * Returns a list of problems; an empty list means the layout is valid.
 */
export function validateLayout(layout: any): string[] {
  const errors: string[] = [];

  if (!layout || typeof layout !== 'object') {
    return ['Layout must be an object'];
  }
  if (layout.version !== 1) {
    errors.push('Unsupported layout version');
  }
  const { screen } = layout;
  if (!screen || typeof screen !== 'object'
    || !Number.isFinite(screen.width) || !Number.isFinite(screen.height)
    || screen.width < 100 || screen.width > 10000
    || screen.height < 100 || screen.height > 10000) {
    errors.push('Layout must have a screen with a width and height between 100 and 10000');
  }
  if (!layout.root || layout.root.type !== 'container') {
    errors.push('Layout root must be a container');
    return errors;
  }

  let nodeCount = 0;
  const seenIds = new Set<string>();

  const visit = (node: any, depth: number): void => {
    nodeCount++;
    if (nodeCount > MAX_NODES) return;
    if (depth > MAX_DEPTH) {
      errors.push('Layout is nested too deep');
      return;
    }
    if (!node || typeof node !== 'object') {
      errors.push('Node must be an object');
      return;
    }
    if (typeof node.id !== 'string' || node.id.length === 0 || node.id.length > 64) {
      errors.push('Every node needs an id (max 64 chars)');
    } else if (seenIds.has(node.id)) {
      errors.push(`Duplicate node id: ${node.id}`);
    } else {
      seenIds.add(node.id);
    }
    if (node.weight !== undefined && (!Number.isFinite(node.weight) || node.weight <= 0 || node.weight > 100)) {
      errors.push(`Node ${node.id}: weight must be a number between 0 and 100`);
    }

    switch (node.type) {
      case 'container':
        if (node.direction !== 'row' && node.direction !== 'column') {
          errors.push(`Container ${node.id}: direction must be "row" or "column"`);
        }
        if (!Array.isArray(node.children)) {
          errors.push(`Container ${node.id}: children must be an array`);
        } else {
          node.children.forEach((child: any) => visit(child, depth + 1));
        }
        break;
      case 'button':
        if (typeof node.label !== 'string') {
          errors.push(`Button ${node.id}: label must be a string`);
        }
        if (typeof node.scene !== 'string' || node.scene.length === 0) {
          errors.push(`Button ${node.id}: scene name is required`);
        }
        break;
      case 'slider':
        if (node.name !== undefined
          && (typeof node.name !== 'string' || node.name.length === 0 || node.name.length > 64)) {
          errors.push(`Slider ${node.id}: name must be a non-empty string (max 64 chars)`);
        }
        if (node.labels !== undefined
          && (!Array.isArray(node.labels) || node.labels.some((l: any) => typeof l !== 'string'))) {
          errors.push(`Slider ${node.id}: labels must be an array of strings`);
        }
        if (node.levels !== undefined) {
          if (!Array.isArray(node.levels) || node.levels.length < 2 || node.levels.length > MAX_SLIDER_LEVELS) {
            errors.push(`Slider ${node.id}: levels must be an array of 2-${MAX_SLIDER_LEVELS} entries`);
          } else if (node.levels.some((level: any) => !level || typeof level !== 'object'
            || typeof level.name !== 'string' || level.name.length > 40
            || !Number.isFinite(level.value) || level.value < 0 || level.value > 1)) {
            errors.push(`Slider ${node.id}: each level needs a name (max 40 chars) and a value between 0 and 1`);
          }
        }
        break;
      case 'label':
        if (typeof node.text !== 'string') {
          errors.push(`Label ${node.id}: text must be a string`);
        }
        break;
      default:
        errors.push(`Unknown node type: ${node.type}`);
    }
  };

  visit(layout.root, 0);

  if (nodeCount > MAX_NODES) {
    errors.push(`Layout has too many nodes (max ${MAX_NODES})`);
  }

  return errors;
}
